version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: PostgresCont
    restart: always
    environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres123
    - POSTGRES_DB=riverradar_service
    ports:
    - '5432:5432'
    volumes:
    - postgres:/var/lib/postgresql/data
volumes:
  postgres:
    driver: local